project_id = "mid-manager"
[api]
enabled = true
[db]
port = 54322
shadow_port = 54320
major_version = 17
[studio]
enabled = true
[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173/**"]